### ISSUE TITLE
How to remove default selected tab when fragment was attached !

### ISSUE THREAD

**Issue by deshario** [vkalmath/expandable_bottom_tab#2]
![image](https://cloud.githubusercontent.com/assets/11426727/26557349/f7e9e25c-44ca-11e7-8116-bab45e9aead3.png)

Hi Sir ! Is there any way to remove default selected tab when app starts or fragment was loaded! 
When my Fragment was loaded .... it will default selected or it will be in selected mode (black color icon) ... can i config it ! Thankyou

**Comment by vkalmath** [comment]
change resetFocusOnAllTabs public and replace the below code to ExpandableBottomTabBar.java

and use it resetFocusOnAllTabs() wherever u need it. Will commit my changes later.


public void resetFocusOnAllTabs() {
        for (View textView : mTabViewList) {
            ((TextView) textView).setTextColor(mTabTextColor);
        }

        for(int i = 0; i < mTabViewList.size(); i++ ){
            ((TextView) mTabViewList.get(i))
                    .setCompoundDrawablesRelativeWithIntrinsicBounds(0, mTabInfoList.get(i).iconResId, 0, 0);
        }
    }

**Comment by vkalmath** [comment]
Merged this to master.

**Comment by deshario** [comment]
Sir ! It's not working ! No Changes .... It was still default selected with
black icon !
[image: Inline image 1]

**Comment by deshario** [comment]
Sir ! It's still not working ! Still  Default Selected with black icon !
[image: Inline image 1]

**Comment by vkalmath** [comment]
Are you calling resetFocusOnAllTabs() ?
ex:
ExpandableBottomTabBar tabBarView = (ExpandableBottomTabBar) findViewById(R.id.tab_bar);
tabBarView.resetFocusOnAllTabs();

**Comment by deshario** [comment]
Thanku Sir ! It's Working now ... Actually there was some problem with my
android studio ...  But now its ok .. Thanku
