### ISSUE TITLE
Hide Tab Item

### ISSUE THREAD

**Issue by vaithitheone** [vkalmath/expandable_bottom_tab#5]
Hi,

 How Can I Hide I Tab item From It Position,Like tabBarview.setHideTabAt(0);or with ID

**Comment by vkalmath** [comment]
what is the use case u r referring to? The tab count is fixed from the attributes.
There is `private View getTabViewAt(int position)` method. Make it public and try to use it to set the visibility of the view.

**Comment by vaithitheone** [comment]
Yeah!!! It's Working Thank You So Much
